### ISSUE TITLE
When deploying a contract the name of it has to be provided twice

### ISSUE THREAD

**Issue by itamararjuan** [orbs-network/orbs-contract-sdk#1]
a bit redundant and error prone.

We should discuss this in more detail

**Comment by talkol** [comment]
We had a bug where we provided a different name in the cli than what appears in the contract code itself.. and it took a long time to figure out the issue

**Comment by EsterEdelstein** [comment]
Can we avoid writing the contract name twice by relaying on the contract name in the file provided ?
