### ISSUE TITLE
installation issue - #2

### ISSUE THREAD

**Issue by EsterEdelstein** [orbs-network/orbs-contract-sdk#10]
From Andrey: 
I've encountered some issues with Gamma installation:
1. See the attached screenshot.
It seems that not all tools are downloaded - specifically, jsonapi is missing, so gamma-cli doesn't get compiled. 
I think the issue is with this line:

git fetch --all && git checkout feature/gamma-cli

**Comment by itamararjuan** [comment]
The issue appears to be a small typo coming from yesterday's code review of the feature prior to merging it to master.

**Comment by itamararjuan** [comment]
Fixed the typo in the install script in addition to 2 more small bugs which I found
the script has been tested on a fresh ubuntu installation with only Go installed and ran the entire scenarion from install to running the server and deploying + interacting with the contract. All looks good.
