### ISSUE TITLE
Extra . in path to run gamma-server after installation

### ISSUE THREAD

**Issue by DrorTrieman** [orbs-network/orbs-contract-sdk#13]
After an installation, when try to run gamma-server start, it fails because it tries to run from the path ./usr/local/bin/gamma-server.
If I try to run from /usr/local/bin/gamma-server it works.

**Comment by netoneko** [comment]
Fixed in https://github.com/orbs-network/orbs-network-go/pull/234/commits/1f95462504947b3cd35c5589b0a15e687a9087df
