### ISSUE TITLE
Gamma installation conflicts with Orbs Core developer  env.

### ISSUE THREAD

**Issue by ronnno** [orbs-network/orbs-contract-sdk#24]
Gamma installation checks out two repositories under $GOPATH, compiles there, and leaves the keys files in the repository folder. This collides with working on the repos and interferes with dev experience.

For instance, the installation script does not work when there are already changes in the workdir folder (and it also fails to abort in this case, leaving to version collisions, see  #22 ) but even if there are no changes, it leaves the workdir in the gamma version tag:
```
➜  orbs-network-go git:(5039a4f) git status
HEAD detached at v0.1-gamma
```

Suggest:
```
# setup temp GOPATH
export GOPATH=`mktemp -d -t gamma-install-gopath`
function cleanup {      
  rm -rf "$GOPATH"
  echo "Deleted temp working directory $GOPATH"
} 
trap cleanup EXIT

# ... rest of the script as it is today ...

# ... copy artifacts outside of temp dir (/opt/orbs/gamma/v1/bin with symlinks to /opt/bin?) before setting symlinks ...
```

**Comment by ronnno** [comment]
I see there is some complication with the genKeys script option - it relies on the GOPATH to stay constant.

Recommend to move installation to `/opt/orbs/gamma/v1/bin` and save the keys under `/etc/opt/orbs/gamma/v1` or something similar...

**Comment by EsterEdelstein** [comment]
Suggested solutions by Ron :
1. Hold complied version in github , installation will download that + a need in installer.  
2. When downloading the file - download the sources to a temporary gopath and then move the compiled files to the desired path (path.

**Comment by talkol** [comment]
Resolved in new gamma version
