### ISSUE TITLE
On responses via Gamma - blockhight is wrong.

### ISSUE THREAD

**Issue by EsterEdelstein** [orbs-network/orbs-contract-sdk#26]
{"OutputArguments":[{"Name":"uint64","Type":"uint64","Value":600}],"CallResult":1,"BlockHeight":7347,"BlockTimestamp":0}.
Problem with the “Name” field

Blocktimestamp- is always 0. 

BlockHeight - also looks like a random number.

**Comment by talkol** [comment]
Block height is not wrong.. the system is closing blocks very quickly so empty blocks are closed when the server is idle.

We can slow the rate down, but that will mean that if you send a transaction you will wait this time.

Meaning if block time was 1 second, then when you send a transaction you may need to wait up to a second until you get a response.

What time do you want?
