### ISSUE TITLE
gamma-cli status

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#35]
when running the gamma-cli status the following error appears: 

ERROR:
  status request failed on gamma server

failed decoding response: response is corrupt and cannot be decoded.

![screen shot 2018-12-05 at 16 26 19](https://user-images.githubusercontent.com/45359306/49519983-f5fe1b80-f8aa-11e8-8557-fe3abb15571e.png)

**Comment by EsterEdelstein** [comment]
@eyalorbs please try to update gamma and then see if this happens again. 
gamma-cli upgrade

**Comment by talkol** [comment]
yes, you have an old version of both

`brew upgrade gamma-cli`
`gamma-cli upgrade-server`
