### ISSUE TITLE
gamma-cli upgrade

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#37]
the command gamma-cli upgrade doesn't work
![screen shot 2018-12-05 at 18 50 50](https://user-images.githubusercontent.com/45359306/49529496-cce78600-f8be-11e8-9ce2-02421acce40a.png)

**Comment by talkol** [comment]
```
brew upgrade gamma-cli
gamma-cli upgrade-server
```
