### ISSUE TITLE
When  typing gamma-cli stop-local when sever is already stooped - misleading error. 

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#39]
I got an unexpected error when I ran the command: "gamma-cli stop-local" when gamma wasn't running.

![screen shot 2018-12-06 at 12 23 14](https://user-images.githubusercontent.com/45359306/49578325-2d73d300-f952-11e8-9c36-fb4c4a33a1d6.png)

**Comment by talkol** [comment]
which version?

**Comment by eyalorbs** [comment]
version v0.5.2-beta

**Comment by talkol** [comment]
need to fix
