### ISSUE TITLE
ERC20 example uses deprecated SDK

### ISSUE THREAD

**Issue by electricmonk** [orbs-network/orbs-contract-sdk#40]

**Comment by EsterEdelstein** [comment]
Can you elaborate ? do you mean the current ERC 20 example in [here](https://github.com/orbs-network/orbs-contract-sdk/tree/master/go/examples/erc20token) or do you refer to the benchmark token?

**Comment by electricmonk** [comment]
the former

**Comment by talkol** [comment]
Removed the example
