### ISSUE TITLE
automatic 10 new test keys

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#45]
1) When starting gamma-cli it automatically creates 10 new test keys. This seems unnecessary because 10 test keys are created when deploying a smart contract.

2) The test keys are generated inside the working directory. I think it would be more comfortable if the test keys would be generated in the directory of the smart contract. That way you won't end up finding a bunch of orbs-test-keys.json all over your computer (depending what your working directory was when you deployed the contract).

**Comment by EsterEdelstein** [comment]
Closing this.
1. additional feedback , indicates on the need to create the file in advance.
In regards to number #2 - we shell wait for more feedback. Less urgent for now.
