### ISSUE TITLE
append crash

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#52]
the following lines make the append crash the smart contract:

![screen shot 2018-12-19 at 23 00 52](https://user-images.githubusercontent.com/45359306/50247934-f7b6fb80-03e1-11e9-9e31-55be1299ecc7.png)

this is the json file used to call this function: 

![screen shot 2018-12-19 at 23 01 51](https://user-images.githubusercontent.com/45359306/50247975-174e2400-03e2-11e9-99d9-ea236cc5ab7b.png)

this is the error:
ERROR:
  Request send-tx failed on Gamma server.

failed decoding response: reserved ExecutionResult received

**Comment by EsterEdelstein** [comment]
@eyalorbs  can you attach the contract you are trying to send tx as a file  to here

**Comment by eyalorbs** [comment]
I changed the transferFrom function and it works, although I am not sure why the previous one that I wrote did not work

[erc20.txt](https://github.com/orbs-network/orbs-contract-sdk/files/2698733/erc20.txt)

**Comment by EsterEdelstein** [comment]
@eyalorbs  can you reproduce it in the new gamma version?

**Comment by EsterEdelstein** [comment]
Closing it, as we can not reproduce
