### ISSUE TITLE
Change syntax of commands with required arguments

### ISSUE THREAD

**Issue by gilda** [orbs-network/orbs-contract-sdk#53]
Do we want gamma-cli commands with required arguments to not use the options syntax?

for example:
`gamma-cli deploy -name <name> -code <path to code>`
should be: 
`gamma-cli deploy <name> <path to code>`

Current syntax is a bit confusing.
Could maybe add a default parameter to `-name` option to create a full suite of default values. 

relevant commands are:
- `gamma-cli deploy`
- `gamma-cli send-tx`
- `gamma-cli read`
- `gamma-cli status`

**Comment by EsterEdelstein** [comment]
Hi Gil, 
This is seems the convention in other tools that I looked at, having said that- let sit in person next time you are here to discuss and see how we can improve taking into account all the variables.

**Comment by talkol** [comment]
Due to the autonomous integration, several in our team really worked with gamma-cli and repeated the same feedback

Let's give it a try

https://github.com/orbs-network/orbs-client-sdk-go/commit/1714ced66cc9ad034d9a7f15a6ebad28f9edbfc0
