### ISSUE TITLE
smart contract cannot get it's own address

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#65]
a contract cannot get it's own address. this feature is very helpful. [here is how a contract gets it's own address in ethereum](https://ethereum.stackexchange.com/questions/29469/is-addressthis-a-valid-address-in-a-contracts-constructor?rq=1)

**Comment by talkol** [comment]
Closed in https://github.com/orbs-network/orbs-contract-sdk/commit/45ff00640dd754d3ce141d7f6fd6d5c47bbaa11d
