### ISSUE TITLE
getting the address of a contract & my "own" contract

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#71]
I think that the following two methods will be very helpful:
getMyOwnAddress() - A method that is called by a contract in order to get it's own address
getAddressByContractName() - a method that returns the address of a contract by it's name. (maybe there should also be an error or a warning if there is no contract with that name that is deployed)

**Comment by talkol** [comment]
Closed in https://github.com/orbs-network/orbs-contract-sdk/commit/45ff00640dd754d3ce141d7f6fd6d5c47bbaa11d
