### ISSUE TITLE
ethereum.CallMethod doesn't work

### ISSUE THREAD

**Issue by eyalorbs** [orbs-network/orbs-contract-sdk#75]
ethereum.CallMethod doesn't work. The error message suggests that it is because gamma doesn't recognize v1.
these are the screenshots from the terminal:

![screen shot 2019-01-06 at 13 56 35](https://user-images.githubusercontent.com/45359306/50735633-fbf16000-11ba-11e9-967b-904e9c20e0b7.png)
![screen shot 2019-01-06 at 13 57 05](https://user-images.githubusercontent.com/45359306/50735636-014eaa80-11bb-11e9-9032-60a1f6cb495a.png)

**Comment by noambergIL** [comment]
fixed some time ago
